version: '3'
services:
    php:
        container_name: php
        build: ./php/
        volumes:
            - /home/jonathan/Sites/:/var/www/html/
            - /home/jonathan/.dotfiles/docker/web/apache/sites-enabled/:/etc/apache2/sites-enabled
        ports:
            - 80:80
            - 443:443
        restart: always
    mysql:
        container_name: mysql
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always
