#!/usr/bin/sh

count=$(ssh homeServer -t checkupdates | wc -l)
if [ "$count" = "0" ]; then
	echo ""
else
	echo $count
	echo $count
	if [ "$count" -gt "5" ]; then
		echo "#FFOOOO"
	else
		echo "#FF8000"
	fi
fi
