#!/usr/bin/sh


COMMAND="playerctl --player=$BLOCK_INSTANCE"

case $BLOCK_BUTTON in
	1) $COMMAND previous ;;
	3) $COMMAND next ;;
esac


if [ "$($COMMAND status)" = "Playing" ]; then
	colour="#00FF00"
else
	colour="#FF8000"
fi

ret="<span foreground='$colour'>$($COMMAND metadata title)</span>"
ret="$ret - $($COMMAND metadata artist)"

echo "$ret";
