#!/usr/bin/sh


#COMMAND="playerctl --player=$BLOCK_INSTANCE"
COMMAND="playerctl"

case $BLOCK_BUTTON in
	1) $COMMAND previous ;;
	3) $COMMAND next ;;
esac


if [ "$($COMMAND status)" = "Playing" ]; then
	colour="#00FF00"
else
	colour="#FF8000"
fi

title=$($COMMAND metadata title | sed "s/\&/\&amp;/g")
artist=$($COMMAND metadata artist | sed "s/\&/\&amp;/g")

if [ "$title" != "(null)" ]; then
	ret="<span foreground='$colour'>$title</span>"
	if [ -n "$artist" ]; then
		ret="$ret - $artist"
	fi

	echo "$ret";
fi



