#!/usr/bin/sh


COMMAND="playerctl --player=$BLOCK_INSTANCE"

case $BLOCK_BUTTON in
	1) $COMMAND previous ;;
	3) $COMMAND next ;;
esac


if [ "$($COMMAND status)" = "Playing" ]; then
	colour="#00FF00"
else
	colour="#FF8000"
fi

title=$($COMMAND metadata title | sed "s/\&/\&amp;/g")
artist=$($COMMAND metadata artist | sed "s/\&/\&amp;/g")


ret="<span foreground='$colour'>$title</span>"
ret="$ret - $artist"



echo "$ret";
