#!/usr/bin/sh

if ! command -v checkupdates > /dev/null; then
	echo "You need to install checkupdates";
	echo "";
	echo "#FF0000"
else
	count=$(checkupdates | wc -l)
	if [ "$count" = "0" ]; then
		echo ""
		echo ""
		echo ""
		exit 0
	fi
	echo "$label $count"
	echo "$label $count"
	if [ "$count" -gt "5" ]; then
		echo "#FFOOOO"
	else
		echo "#FF8000"
	fi
fi
