# Make keyboard layout coleemak but pushing both shifts will toggle to qwerty
setxkbmap -layout gb,gb -variant "colemak," -option grp:shifts_toggle
# Make key firing much faster
xset r rate 200 70
# Need this for making qt applications use gtk theme ( I think )
export QT_QPA_PLATFORMTHEME=qt5ct
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export _JAVA_AWT_WM_NONREPARENTING=1
# Use gnome keyring
killall gnome-keyring-d 2> /dev/null
export `gnome-keyring-daemon -d`
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY
#exec xrdb .Xresources
#xbindkeys
#exec i3 -V >> ~/i3log-$(date + '%F-%k-%M-%S') 2>&1
while :; do
	dwm
done;
#exec sh /home/jonathan/.conky/conky-startup.sh
#xcape
