#!/usr/bin/sh
selection=$( \
	echo -e "Lock\nLogout\nSuspend\nHibernate\nReboot\nShutdown" |\
	rofi -dmenu -i -p 'Option');
echo $selection;

sleep .2

case $selection in
	Lock)
		~/.config/i3/i3exit lock
		;;
	Logout)
		~/.config/i3/i3exit logout
		;;
	Suspend)
		~/.config/i3/i3exit suspend
		;;
	Hibernate)
		~/.config/i3/i3exit hibernate
		;;
	Reboot)
		~/.config/i3/i3exit reboot
		;;
	Shutdown)
		~/.config/i3/i3exit shutdown
		;;
esac
